name: Build and deploy
on:
  push:
    branches:
      - development
      - feature/staging-deployment-pipeline-updated

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and deploy web app
    steps:
      - uses: actions/checkout@v1
      - name: Install env dependencies
        env:
          CI: false
          REACT_APP_API_URL: ''
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_CI_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_CI_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          GITHUB_DEPLOYMENT_TOKEN: ${{ secrets.GH_DEPLOYMENT_TOKEN }}
        run: |
          npm install --global yarn -y
          pip install awscli
          yarn
          yarn build-staging-client
          zip -r build.zip build/
          echo "`node -e "console.log(Date.now())"`" > .versionCode
          aws s3 cp build.zip s3://brij-deployment-assets/consumer-app-v2/builds/`cat .versionCode`
          curl -X POST -H "Accept: application/json" https://eew8kgj9bh.execute-api.us-east-1.amazonaws.com/deploy-consumer-app-client -d '{ "stage": "staging", "versionCode": "`cat .versionCode`" }'
