name: Functional test

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  installDependencies:
    name: Functional test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      uses: actions/setup-node@v2
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        args: npm install
    - name: Install deps
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      run: |
        sh -c 'cd test && npm install'
    - name: Test Code
      uses: mujo-code/puppeteer-headful@v2
      env:
        CI: 'true'
      with:
        args: npm test:functional